### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by tynandebold** [holub008/MediocreAmateur#1]
Is this project still maintained? It would be great to get it up to date with the YouTube videos.

**Comment by holub008** [comment]
Hi @tynandebold I haven't been updating (or fully automated updates) because it requires some manual work (linking up strava, doing some detective work where to drop a pin, etc.). That said, it would be great to update :)

**Comment by holub008** [comment]
Ugh - google has ruined their Youtube API offering for small projects like this:

1. Billing information is required to get a quota
2. In order to request a bump in quota from 0 requests/day, you have to fill out a shitty "YouTube API Services - Audit and Quota Extension Form", which seems to include periodic audit of the application.

I have no interest in either for a project like this. Maybe I'll find the motivation to update manually (or similarly, anyone else)!

**Comment by tynandebold** [comment]
Agreed. Thanks for the update.

**Comment by holub008** [comment]
Manually brought it up to date :)

(may take up to a day for updates to be reflected in the deployment)

**Comment by tynandebold** [comment]
Legend! Thank you.
